### ISSUE TITLE
How to get .csv file?

### ISSUE THREAD

**Issue by KeshavaShreenidhi** [wilhelmzeuschner/arduino_thermal_camera_with_sd_and_img_processing#2]
Hello 
I am using amg8833 sensor with raspberry pi. And I am not able to get .csv file from the sensor. but I am getting something like this
['24.8', '24.8', '25.0', '25.0', '26.0', '25.8', '25.8', '26.0']
['25.0', '25.2', '25.5', '25.0', '25.2', '26.2', '25.2', '25.8']
['25.2', '24.8', '24.8', '25.0', '25.0', '25.5', '25.5', '26.0']
['25.0', '25.2', '25.0', '25.5', '26.0', '26.0', '25.8', '25.8']
['25.0', '24.8', '25.0', '25.5', '31.2', '25.8', '25.2', '25.2']
['25.2', '24.2', '25.0', '25.2', '25.5', '25.5', '25.5', '25.0']
['24.8', '24.2', '24.8', '25.0', '25.5', '25.5', '25.5', '25.2']
['24.5', '25.2', '25.8', '25.2', '25.0', '25.5', '25.0', '25.0']

this kinda matches with your old data (IMAGE_07.TXT).

And also I have tried these code in raspberry pi with the example data (that you have given) but I am getting error. I have attached a copy of the error that I am getting.
![error](https://user-images.githubusercontent.com/44582878/61193157-52de7180-a6d7-11e9-9135-300af206d52f.png)

Thank you

**Comment by wilhelmzeuschner** [comment]
It seems like you did save an 8x8 image. The python scrip expects 70x70 (interpolated) data.
